"""empty message

Revision ID: 237a833cf043
Revises: ff4e742a1f8c
Create Date: 2025-10-01 08:32:06.384386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '237a833cf043'
down_revision = 'ff4e742a1f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stories', schema=None) as batch_op:
        batch_op.alter_column('EVIDENCE_FILE',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stories', schema=None) as batch_op:
        batch_op.alter_column('EVIDENCE_FILE',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
