"""empty message

Revision ID: 28e2b1c4fc95
Revises: a7ba4e6d1c3f
Create Date: 2025-10-13 09:11:14.623469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e2b1c4fc95'
down_revision = 'a7ba4e6d1c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_comment',
    sa.Column('ID_COMMENT', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_ISSUE', sa.Integer(), nullable=False),
    sa.Column('ID_USER', sa.Integer(), nullable=True),
    sa.Column('ID_TEAM', sa.Integer(), nullable=True),
    sa.Column('CONTENT', sa.Text(), nullable=False),
    sa.Column('CREATED_AT', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ID_ISSUE'], ['issues.ID_ISSUE'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ID_TEAM'], ['team.ID_TEAM'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ID_USER'], ['users.ID_USER'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ID_COMMENT')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_comment')
    # ### end Alembic commands ###
