"""recreate issue_resolve table clean

Revision ID: 3d5556caa3b3
Revises: d22ad9346260
Create Date: 2025-10-06 15:47:25.979800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5556caa3b3'
down_revision = 'd22ad9346260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_resolve',
    sa.Column('ID_RESOLVE', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.ID_ISSUE'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.ID_TEAM'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ID_RESOLVE'),
    sa.UniqueConstraint('issue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_resolve')
    # ### end Alembic commands ###
