"""empty message

Revision ID: 40ff1067f822
Revises: c01a2431441e
Create Date: 2025-10-08 09:37:31.663298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ff1067f822'
down_revision = 'c01a2431441e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DUE_DATE', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('DUE_DATE')

    # ### end Alembic commands ###
