"""empty message

Revision ID: 413df6f911a4
Revises: bcff428bf307
Create Date: 2025-09-24 11:25:43.725310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '413df6f911a4'
down_revision = 'bcff428bf307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_status',
    sa.Column('ID_status', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ID_status')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name_role'))

    op.drop_table('role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id_role', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name_role', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_role'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name_role'), ['name_role'], unique=True)

    op.drop_table('workflow_status')
    # ### end Alembic commands ###
