"""empty message

Revision ID: 4340653fd542
Revises: cf5caa677506
Create Date: 2025-09-30 09:40:09.292594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4340653fd542'
down_revision = 'cf5caa677506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stories', schema=None) as batch_op:
        batch_op.alter_column('ID_SPRINT',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stories', schema=None) as batch_op:
        batch_op.alter_column('ID_SPRINT',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
