"""empty message

Revision ID: 53b788ace58b
Revises: e2afa2ad8d38
Create Date: 2025-09-26 14:05:03.564953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b788ace58b'
down_revision = 'e2afa2ad8d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projectrole', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('projectrole_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['ID_PROJECT'], ['ID_PROJECT'], ondelete='CASCADE')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('team_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projectrole', ['ID_PROJROLE'], ['ID_PROJROLE'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('team_ibfk_1'), 'projectrole', ['ID_PROJROLE'], ['ID_PROJROLE'])

    with op.batch_alter_table('projectrole', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('projectrole_ibfk_1'), 'project', ['ID_PROJECT'], ['ID_PROJECT'])

    # ### end Alembic commands ###
