"""allow multiple resolves per issue

Revision ID: 6ef1f32478de
Revises: 28e2b1c4fc95
Create Date: 2025-10-15 09:01:02.414196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef1f32478de'
down_revision = '28e2b1c4fc95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_resolve', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('issue_id'))
          pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_resolve', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('issue_id'), ['issue_id'], unique=True)

    # ### end Alembic commands ###
