"""empty message

Revision ID: 743236e3b91c
Revises: 237a833cf043
Create Date: 2025-10-02 09:29:03.689179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '743236e3b91c'
down_revision = '237a833cf043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hashtag', schema=None) as batch_op:
        batch_op.alter_column('NAME',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('user_stories', schema=None) as batch_op:
        batch_op.alter_column('DESCRIPTION',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stories', schema=None) as batch_op:
        batch_op.alter_column('DESCRIPTION',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('hashtag', schema=None) as batch_op:
        batch_op.alter_column('NAME',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
