"""empty message

Revision ID: 7795a5e8d2da
Revises: 29f0827de47d
Create Date: 2025-10-03 21:05:08.582011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7795a5e8d2da'
down_revision = '29f0827de47d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID_PROJROLE', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('team_invite_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projectrole', ['ID_PROJROLE'], ['ID_PROJROLE'])
        batch_op.drop_column('ID_ROLE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID_ROLE', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('team_invite_ibfk_2'), 'role', ['ID_ROLE'], ['ID_ROLE'])
        batch_op.drop_column('ID_PROJROLE')

    # ### end Alembic commands ###
