"""empty message

Revision ID: 9d0af86cac56
Revises: 743236e3b91c
Create Date: 2025-10-03 10:37:26.984955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d0af86cac56'
down_revision = '743236e3b91c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=500), nullable=True))
        batch_op.alter_column('skillset',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('skillset',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
