"""sync after IS_CUSTOM error

Revision ID: b5fee5fc744f
Revises: e0d5aa036e45
Create Date: 2025-10-06 12:00:05.718271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5fee5fc744f'
down_revision = 'e0d5aa036e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_resolve',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.ID_ISSUE'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.ID_TEAM'], ),
    sa.PrimaryKeyConstraint('team_id', 'issue_id')
    )
    with op.batch_alter_table('projectrole', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NAME_ROLE', sa.String(length=100), nullable=False))
        batch_op.alter_column('ID_ROLE',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('team_invite', schema=None) as batch_op:
        batch_op.drop_column('ID_ROLE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID_ROLE', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    with op.batch_alter_table('projectrole', schema=None) as batch_op:
        batch_op.alter_column('ID_ROLE',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('NAME_ROLE')

    op.drop_table('issue_resolve')
    # ### end Alembic commands ###
