"""allow team_id null in issue_resolve

Revision ID: bc98af0e36d4
Revises: b5fee5fc744f
Create Date: 2025-10-06 15:28:36.665686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc98af0e36d4'
down_revision = 'b5fee5fc744f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_resolve', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_resolve', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
