"""empty message

Revision ID: bcff428bf307
Revises: 2319565a753b
Create Date: 2025-09-24 10:55:13.914394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcff428bf307'
down_revision = '2319565a753b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id_role', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_role', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_role'),
    sa.UniqueConstraint('name_role')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    # ### end Alembic commands ###
