"""change issue_resolve to have ID_RESOLVE primary key

Revision ID: d22ad9346260
Revises: bc98af0e36d4
Create Date: 2025-10-06 15:37:08.868492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd22ad9346260'
down_revision = 'bc98af0e36d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_resolve', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID_RESOLVE', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.alter_column('team_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.create_unique_constraint(None, ['issue_id'])
        batch_op.drop_constraint(batch_op.f('issue_resolve_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('issue_resolve_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'issues', ['issue_id'], ['ID_ISSUE'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'team', ['team_id'], ['ID_TEAM'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_resolve', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('issue_resolve_ibfk_2'), 'team', ['team_id'], ['ID_TEAM'])
        batch_op.create_foreign_key(batch_op.f('issue_resolve_ibfk_1'), 'issues', ['issue_id'], ['ID_ISSUE'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('team_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('ID_RESOLVE')

    # ### end Alembic commands ###
