"""empty message

Revision ID: d93ac653e032
Revises: 9d0af86cac56
Create Date: 2025-10-03 12:48:35.236058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd93ac653e032'
down_revision = '9d0af86cac56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projectrole', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NAME_ROLE', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('IS_CUSTOM', sa.Boolean(), nullable=False))
        batch_op.alter_column('ID_ROLE',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projectrole', schema=None) as batch_op:
        batch_op.alter_column('ID_ROLE',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('IS_CUSTOM')
        batch_op.drop_column('NAME_ROLE')

    # ### end Alembic commands ###
