"""empty message

Revision ID: e60d46743107
Revises: 9d0af86cac56
Create Date: 2025-10-03 13:37:36.016429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e60d46743107'
down_revision = '9d0af86cac56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projectrole', schema=None) as batch_op:
        batch_op.alter_column('ID_ROLE',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('NAME_ROLE')
        batch_op.drop_column('IS_CUSTOM')

    with op.batch_alter_table('team_invite', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'project', ['ID_PROJECT'], ['ID_PROJECT'])
        batch_op.create_foreign_key(None, 'role', ['ID_ROLE'], ['ID_ROLE'])
        batch_op.drop_column('ID_PROJROLE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID_PROJROLE', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('projectrole', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IS_CUSTOM', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('NAME_ROLE', mysql.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('ID_ROLE',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
