"""add team invite

Revision ID: ff4e742a1f8c
Revises: 4340653fd542
Create Date: 2025-09-30 10:50:02.157682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4e742a1f8c'
down_revision = '4340653fd542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_invite',
    sa.Column('ID_INVITE', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_PROJECT', sa.Integer(), nullable=False),
    sa.Column('ID_ROLE', sa.Integer(), nullable=False),
    sa.Column('EMAIL', sa.String(length=150), nullable=False),
    sa.Column('STATUS', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ID_PROJECT'], ['project.ID_PROJECT'], ),
    sa.ForeignKeyConstraint(['ID_ROLE'], ['role.ID_ROLE'], ),
    sa.PrimaryKeyConstraint('ID_INVITE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_invite')
    # ### end Alembic commands ###
