"""Init user

Revision ID: 2319565a753b
Revises: a46443ad1000
Create Date: 2025-09-23 16:13:05.230116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2319565a753b'
down_revision = 'a46443ad1000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('ID_act', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name_act', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ID_act')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action')
    # ### end Alembic commands ###
