"""empty message

Revision ID: e2afa2ad8d38
Revises: e7ceb7a9d13a
Create Date: 2025-09-25 12:39:18.527871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2afa2ad8d38'
down_revision = 'e7ceb7a9d13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('ID_ACT', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NAME_ACT', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ID_ACT')
    )
    op.create_table('task_status',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NAME_STATUS', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('users',
    sa.Column('ID_USER', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('skillset', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ID_USER'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workflow_status',
    sa.Column('ID_STATUS', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NAME', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ID_STATUS')
    )
    op.create_table('permission_',
    sa.Column('ID_PERM', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_RES', sa.Integer(), nullable=False),
    sa.Column('ID_ACT', sa.Integer(), nullable=False),
    sa.Column('ID_PROJROLE', sa.Integer(), nullable=False),
    sa.Column('IS_ALLOWED', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ID_ACT'], ['action.ID_ACT'], ),
    sa.ForeignKeyConstraint(['ID_PROJROLE'], ['projectrole.ID_PROJROLE'], ),
    sa.ForeignKeyConstraint(['ID_RES'], ['resource.ID_RES'], ),
    sa.PrimaryKeyConstraint('ID_PERM')
    )
    op.create_table('team',
    sa.Column('ID_TEAM', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_PROJROLE', sa.Integer(), nullable=False),
    sa.Column('ID_USER', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_PROJROLE'], ['projectrole.ID_PROJROLE'], ),
    sa.ForeignKeyConstraint(['ID_USER'], ['users.ID_USER'], ),
    sa.PrimaryKeyConstraint('ID_TEAM')
    )
    op.create_table('user_stories',
    sa.Column('ID_USER_STORIES', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_STATUS', sa.Integer(), nullable=False),
    sa.Column('ID_PROJECT', sa.Integer(), nullable=False),
    sa.Column('ID_SPRINT', sa.Integer(), nullable=False),
    sa.Column('NAME_STORIES', sa.String(length=200), nullable=False),
    sa.Column('DESCRIPTION', sa.Text(), nullable=False),
    sa.Column('EXPIRE_DATE', sa.Date(), nullable=False),
    sa.Column('EVIDENCE_FILE', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['ID_PROJECT'], ['project.ID_PROJECT'], ),
    sa.ForeignKeyConstraint(['ID_SPRINT'], ['sprints.ID_SPRINT'], ),
    sa.ForeignKeyConstraint(['ID_STATUS'], ['workflow_status.ID_STATUS'], ),
    sa.PrimaryKeyConstraint('ID_USER_STORIES')
    )
    op.create_table('complexity_point',
    sa.Column('ID_COMPLEXITY', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_USER_STORIES', sa.Integer(), nullable=False),
    sa.Column('NAME', sa.String(length=100), nullable=False),
    sa.Column('POINT', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ID_USER_STORIES'], ['user_stories.ID_USER_STORIES'], ),
    sa.PrimaryKeyConstraint('ID_COMPLEXITY')
    )
    op.create_table('task',
    sa.Column('ID_TASK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_USER_STORIES', sa.Integer(), nullable=False),
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('NAME', sa.String(length=200), nullable=False),
    sa.Column('DESCRIPTION', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ID'], ['task_status.ID'], ),
    sa.ForeignKeyConstraint(['ID_USER_STORIES'], ['user_stories.ID_USER_STORIES'], ),
    sa.PrimaryKeyConstraint('ID_TASK')
    )
    op.create_table('user_stories_hashtag',
    sa.Column('ID_USER_STORIES', sa.Integer(), nullable=False),
    sa.Column('ID_HASTAG', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_HASTAG'], ['hashtag.ID_HASTAG'], ),
    sa.ForeignKeyConstraint(['ID_USER_STORIES'], ['user_stories.ID_USER_STORIES'], ),
    sa.PrimaryKeyConstraint('ID_USER_STORIES', 'ID_HASTAG')
    )
    op.create_table('phan_cong',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.ID_TASK'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.ID_TEAM'], ),
    sa.PrimaryKeyConstraint('team_id', 'task_id')
    )
    op.create_table('task_hashtag',
    sa.Column('ID_HASTAG', sa.Integer(), nullable=False),
    sa.Column('ID_TASK', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_HASTAG'], ['hashtag.ID_HASTAG'], ),
    sa.ForeignKeyConstraint(['ID_TASK'], ['task.ID_TASK'], ),
    sa.PrimaryKeyConstraint('ID_HASTAG', 'ID_TASK')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_hashtag')
    op.drop_table('phan_cong')
    op.drop_table('user_stories_hashtag')
    op.drop_table('task')
    op.drop_table('complexity_point')
    op.drop_table('user_stories')
    op.drop_table('team')
    op.drop_table('permission_')
    op.drop_table('workflow_status')
    op.drop_table('users')
    op.drop_table('task_status')
    op.drop_table('action')
    # ### end Alembic commands ###
