"""empty message

Revision ID: e7ceb7a9d13a
Revises: 413df6f911a4
Create Date: 2025-09-25 11:25:28.560497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7ceb7a9d13a'
down_revision = '413df6f911a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtag',
    sa.Column('ID_HASTAG', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NAME', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ID_HASTAG')
    )
    op.create_table('issue_type',
    sa.Column('ID_TYPE', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NAME', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ID_TYPE')
    )
    op.create_table('project',
    sa.Column('ID_PROJECT', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NAME_PROJECT', sa.String(length=200), nullable=False),
    sa.Column('DESCRIPTION', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('ID_PROJECT')
    )
    op.create_table('resource',
    sa.Column('ID_RES', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NAME_RES', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ID_RES')
    )
    op.create_table('role',
    sa.Column('ID_ROLE', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NAME_ROLE', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ID_ROLE')
    )
    op.create_table('issues',
    sa.Column('ID_ISSUE', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_PROJECT', sa.Integer(), nullable=False),
    sa.Column('ID_TYPE', sa.Integer(), nullable=False),
    sa.Column('NAME', sa.String(length=200), nullable=False),
    sa.Column('DESCRIPTION', sa.Text(), nullable=False),
    sa.Column('HASTAG', sa.String(length=100), nullable=False),
    sa.Column('STATUS', sa.Enum('NEW', 'IN_PROGRESS', 'READ_FOR_TEST', 'CLOSED', 'NEED_INFO', 'REJECTED', 'POSTPONED', name='issuestatus'), nullable=False),
    sa.Column('SERVERITY', sa.Enum('WISHLIST', 'MINOR', 'NORMAL', 'IMPORTANT', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('PRIORITY', sa.Enum('LOW', 'NORMAL', 'HIGH', name='priority'), nullable=False),
    sa.Column('EXPIRE_DATE', sa.Date(), nullable=False),
    sa.Column('EVIDENCE_FILE', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['ID_PROJECT'], ['project.ID_PROJECT'], ),
    sa.ForeignKeyConstraint(['ID_TYPE'], ['issue_type.ID_TYPE'], ),
    sa.PrimaryKeyConstraint('ID_ISSUE')
    )
    op.create_table('projectrole',
    sa.Column('ID_PROJROLE', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_ROLE', sa.Integer(), nullable=False),
    sa.Column('ID_PROJECT', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_PROJECT'], ['project.ID_PROJECT'], ),
    sa.ForeignKeyConstraint(['ID_ROLE'], ['role.ID_ROLE'], ),
    sa.PrimaryKeyConstraint('ID_PROJROLE')
    )
    op.create_table('sprints',
    sa.Column('ID_SPRINT', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_PROJECT', sa.Integer(), nullable=False),
    sa.Column('NAME', sa.String(length=100), nullable=False),
    sa.Column('DEADLINE', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['ID_PROJECT'], ['project.ID_PROJECT'], ),
    sa.PrimaryKeyConstraint('ID_SPRINT')
    )
    op.create_table('team',
    sa.Column('ID_TEAM', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_PROJROLE', sa.Integer(), nullable=False),
    sa.Column('ID_USER', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_PROJROLE'], ['projectrole.ID_PROJROLE'], ),
    sa.ForeignKeyConstraint(['ID_USER'], ['users.ID_USER'], ),
    sa.PrimaryKeyConstraint('ID_TEAM')
    )
    op.create_table('user_stories',
    sa.Column('ID_USER_STORIES', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_STATUS', sa.Integer(), nullable=False),
    sa.Column('ID_PROJECT', sa.Integer(), nullable=False),
    sa.Column('ID_SPRINT', sa.Integer(), nullable=False),
    sa.Column('NAME_STORIES', sa.String(length=200), nullable=False),
    sa.Column('DESCRIPTION', sa.Text(), nullable=False),
    sa.Column('EXPIRE_DATE', sa.Date(), nullable=False),
    sa.Column('EVIDENCE_FILE', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['ID_PROJECT'], ['project.ID_PROJECT'], ),
    sa.ForeignKeyConstraint(['ID_SPRINT'], ['sprints.ID_SPRINT'], ),
    sa.ForeignKeyConstraint(['ID_STATUS'], ['workflow_status.ID_STATUS'], ),
    sa.PrimaryKeyConstraint('ID_USER_STORIES')
    )
    op.create_table('complexity_point',
    sa.Column('ID_COMPLEXITY', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_USER_STORIES', sa.Integer(), nullable=False),
    sa.Column('NAME', sa.String(length=100), nullable=False),
    sa.Column('POINT', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ID_USER_STORIES'], ['user_stories.ID_USER_STORIES'], ),
    sa.PrimaryKeyConstraint('ID_COMPLEXITY')
    )
    op.create_table('task',
    sa.Column('ID_TASK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_USER_STORIES', sa.Integer(), nullable=False),
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('NAME', sa.String(length=200), nullable=False),
    sa.Column('DESCRIPTION', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ID'], ['task_status.ID'], ),
    sa.ForeignKeyConstraint(['ID_USER_STORIES'], ['user_stories.ID_USER_STORIES'], ),
    sa.PrimaryKeyConstraint('ID_TASK')
    )
    op.create_table('user_stories_hashtag',
    sa.Column('ID_USER_STORIES', sa.Integer(), nullable=False),
    sa.Column('ID_HASTAG', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_HASTAG'], ['hashtag.ID_HASTAG'], ),
    sa.ForeignKeyConstraint(['ID_USER_STORIES'], ['user_stories.ID_USER_STORIES'], ),
    sa.PrimaryKeyConstraint('ID_USER_STORIES', 'ID_HASTAG')
    )
    op.create_table('phan_cong',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.ID_TASK'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.ID_TEAM'], ),
    sa.PrimaryKeyConstraint('team_id', 'task_id')
    )
    op.create_table('task_hashtag',
    sa.Column('ID_HASTAG', sa.Integer(), nullable=False),
    sa.Column('ID_TASK', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_HASTAG'], ['hashtag.ID_HASTAG'], ),
    sa.ForeignKeyConstraint(['ID_TASK'], ['task.ID_TASK'], ),
    sa.PrimaryKeyConstraint('ID_HASTAG', 'ID_TASK')
    )
    op.create_table('permission_',
    sa.Column('ID_PERM', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_RES', sa.Integer(), nullable=False),
    sa.Column('ID_ACT', sa.Integer(), nullable=False),
    sa.Column('ID_PROJROLE', sa.Integer(), nullable=False),
    sa.Column('IS_ALLOWED', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ID_ACT'], ['action.ID_ACT'], ),
    sa.ForeignKeyConstraint(['ID_PROJROLE'], ['projectrole.ID_PROJROLE'], ),
    sa.ForeignKeyConstraint(['ID_RES'], ['resource.ID_RES'], ),
    sa.PrimaryKeyConstraint('ID_PERM')
    )
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID_ACT', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('NAME_ACT', sa.String(length=100), nullable=False))
        batch_op.drop_column('Name_act')
        batch_op.drop_column('ID_act')

    with op.batch_alter_table('task_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('NAME_STATUS', sa.String(length=100), nullable=False))
        batch_op.drop_column('name_status')
        batch_op.drop_column('id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID_USER', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('workflow_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID_STATUS', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('NAME', sa.String(length=100), nullable=False))
        batch_op.drop_column('ID_status')
        batch_op.drop_column('Name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('ID_status', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('NAME')
        batch_op.drop_column('ID_STATUS')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('ID_USER')

    with op.batch_alter_table('task_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('name_status', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('NAME_STATUS')
        batch_op.drop_column('ID')

    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID_act', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('Name_act', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('NAME_ACT')
        batch_op.drop_column('ID_ACT')

    op.drop_table('task_hashtag')
    op.drop_table('phan_cong')
    op.drop_table('user_stories_hashtag')
    op.drop_table('task')
    op.drop_table('complexity_point')
    op.drop_table('user_stories')
    op.drop_table('team')
    op.drop_table('permission_')
    op.drop_table('sprints')
    op.drop_table('projectrole')
    op.drop_table('issues')
    op.drop_table('role')
    op.drop_table('resource')
    op.drop_table('project')
    op.drop_table('issue_type')
    op.drop_table('hashtag')
    # ### end Alembic commands ###
